---
version: "2"
services:
    alita-redis:
        image: redis:6.2.6-alpine3.15
        restart: always
        networks:
            - shared_alita
        ports:
            - 6379:6379
        logging:
            driver: "json-file"
            options:
                max-size: '100k'
                max-file: '20'