---
version: "2"

services:
    alita-proxy:
        extends:
            file: ./docker/traefik/docker-compose.yml
            service: alita-proxy

    alita-rabbit:
        extends:
            file: ./docker/rabbit/docker-compose.yml
            service: alita-rabbit

    alita-redis:
        extends:
            file: ./docker/redis/docker-compose.yml
            service: alita-redis

#    alita-pg:
#        extends:
#            file: ./docker/database/docker-compose.yml
#            service: alita-pg

    alita-mailcatcher:
        extends:
            file: ./docker/mailcatcher/docker-compose.yml
            service: alita-mailcatcher

    alita-php:
        extends:
            file: ./docker/php/docker-compose.yml
            service: alita-php

    alita-nginx:
        extends:
            file: ./docker/nginx/docker-compose.yml
            service: alita-nginx
networks:
    shared_alita:
        external: false
    proxy_network_alita:
        external: true
