---
version: "2"

services:
    alita-nginx:
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        networks:
            - shared_alita
            - proxy_network_alita
        volumes:
            - ../../public:/srv/alita/public:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=HostRegexp(`web.alita.localhost`)"
            - "traefik.http.routers.frontend.priority=1000"
            - "traefik.http.routers.frontend.entrypoints=web_alita"
            - "traefik.http.routers.frontendhttps.rule=HostRegexp(`web.alita.localhost`)"
            - "traefik.http.routers.frontendhttps.priority=1"
            - "traefik.http.routers.frontendhttps.tls=true"
            - "traefik.http.routers.frontendhttps.entrypoints=websecure_alita"
            - "traefik.http.services.frontend.loadbalancer.server.port=80"
            - "traefik.docker.network=proxy_network_alita"
            - "Project=alita.web"
        logging:
            driver: "json-file"
            options:
                max-size: '100k'
                max-file: '20'