---
version: "2"

services:
    alita-mailcatcher:
        image: stpaquet/alpinemailcatcher
        ports:
            - 1025:1025
            - 8025:8025
        restart: always
        networks:
            - shared_alita
            - proxy_network_alita
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy_network_alita"
            - "traefik.http.routers.mailcatcher.rule=Host(`mail.alita.localhost`)"
            - "traefik.http.routers.mailcatcher.tls=true"
            - "traefik.http.routers.mailcatcher.entrypoints=websecure_alita"
            - "traefik.http.services.mailcatcher.loadbalancer.server.port=1080"
            - "Project=alita.mail"
        logging:
            driver: "json-file"
            options:
                max-size: '100k'
                max-file: '20'
